"""add column confirmed

Revision ID: 0148a0a7b7e6
Revises: 6fb80a0030a0
Create Date: 2023-10-19 16:42:26.110646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0148a0a7b7e6'
down_revision: Union[str, None] = '6fb80a0030a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('firstname', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('lastname', sa.String(length=50), nullable=False))
    op.drop_column('contacts', 'last_name')
    op.drop_column('contacts', 'first_name')
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.add_column('contacts', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'lastname')
    op.drop_column('contacts', 'firstname')
    # ### end Alembic commands ###
